---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-cnpg
  namespace: grafana
spec:
  instances: 3
  storage:
    #storageClass: dcnas-volumes
    size: 1Gi
  bootstrap:
    initdb:
      database: grafana
      owner: admin
      secret:
        name: grafana-db-creds
