apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-creds
  namespace: grafana
type: Opaque
stringData:
  admin-user: admin
  admin-password: "my-new-password"
  username: admin
  password: "my-new-password"
