#!/bin/bash
set -e

: "${GRAFANA_CHART_VERSION:=11.3.10}" # Grafana v11.1.0
: "${K8SAPP_APPLICATION_VERSION:=$GRAFANA_CHART_VERSION}"

# TODO add proxy env vars

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update bitnami

# save the defaults for git diffing later when upgrading
helm pull bitnami/grafana --untar --version "$GRAFANA_CHART_VERSION"
i=grafana
mkdir -p "defaults/$i"
mv "$i/values.yaml" "defaults/$i"
rm -rf "$i"

# TODO pull down and modify templates
