#!/bin/bash
set -e

# shellcheck disable=SC2317
cleanup() {
	stty echo
}
trap cleanup INT EXIT TERM

printf "Enter secret: "
stty -echo
read -r secret
stty echo

helm upgrade grafana grafana/grafana \
	--namespace grafana \
	--set adminPassword="$secret"
